### ISSUE TITLE
Automate publishing getting started configuration package

### ISSUE THREAD

**Issue by turkenh** [upbound/universal-crossplane#184] opened 2021-09-15 10:28 UTC
### What problem are you facing?

Currently, we don't have an automated workflow for build and publish getting started configuration package.

### How could Upbound help solve your problem?

We need to automate similar to how upstream [crossplane's configuration workflows](https://github.com/crossplane/crossplane/blob/master/.github/workflows/configurations.yml).

**Comment by jbw976** [comment] 2022-02-01 03:46
@turkenh is this a dupe of https://github.com/upbound/universal-crossplane/issues/102?  If you think so, you can go ahead and close this one :)

**Closed** 2023-03-27 18:05 UTC
Labels: enhancement, needs-project, needs-epic-link, needs-points-label
