### ISSUE TITLE
Add documentation for supported helm parameters

### ISSUE THREAD

**Issue by hasheddan** [upbound/universal-crossplane#91] opened 2021-05-17 00:11 UTC
### What problem are you facing?

UXP supports configuration for each of its components encompassed by the overall helm chart. It supports all of the values that Crossplane supports, but also additional ones for things like xgql, the agent, and the bootstrapper. However, there is not currently documentation of how these components can be configured.

### How could Universal Crossplane help solve your problem?

It would be awesome to have documentation on parameters and what their behavior does [like Crossplane has](https://github.com/crossplane/crossplane/blob/master/cluster/charts/crossplane/README.md). It might make sense to maintain something like that here, then automatically sync it to the Upbound docs website.

**Comment by phisco** [comment] 2023-02-20 09:17
`xgql` was removed in https://github.com/upbound/universal-crossplane/pull/327, the rest of the issue is still relevant though

**Comment by phisco** [comment] 2023-04-06 18:10
Created this as I feel we should first address it upstream, add the necessary bits to the build submodule and then we can generate the docs automatically for UXP too: https://github.com/crossplane/crossplane/issues/3952. Going the other way round would complicate the values sync step in the release process by a lot as we would have a lot of comments on uxp side that maybe will never or aren't yet upstream.

**Comment by phisco** [comment] 2023-05-04 09:47
Was addressed by @turkenh in https://github.com/upbound/universal-crossplane/pull/364 🎉

**Closed by phisco** 2023-05-04 09:47 UTC
Labels: enhancement
