### ISSUE TITLE
CRD for `aws.upbound.io` not found even after installing `provider-family-aws provider`

### ISSUE THREAD

**Issue by preetsindhal** [upbound/universal-crossplane#396] opened 2023-08-28 05:06 UTC
kind `ProviderConfig` of api `aws.upbound.io` not found even after installing `provider-family-aws` provider

provider is installed with warning:
`Warning  UnpackPackage  24s (x10 over 4m27s)  packages/provider.pkg.crossplane.io  cannot unpack package: failed to fetch package digest from remote: serviceaccounts "crossplane" not found`

Error:

`ProviderConfig/universal-crossplane/aws-provider-upbound dry-run failed: failed to get API group resources: unable to retrieve the complete list of server APIs: aws.upbound.io/v1beta1: the server could not find the requested resource`

Yaml 

```
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: aws-config-upbound
  namespace: universal-crossplane
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::xxxxx:role/K8s-crossplane
spec:
  podSecurityContext:
    fsGroup: 2000
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-family-aws
spec:
  package: xpkg.upbound.io/upbound/provider-family-aws:v0.39.0
  controllerConfigRef:
    name: aws-config-upbound
---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-provider-upbound
  namespace: universal-crossplane
spec:
  credentials:
    source: InjectedIdentity


```

**Comment by saion-chatterjee** [comment] 2023-09-13 17:09
Hi @turkenf I faced the same issue. I am able to reproduce it in the following way:

It seems the uxp installation does not work e2e if the "nameOverride" in values.yaml is anything other than the default value "crossplane". I tried installing it with a different name and the helm chart for uxp is installed but after this the Provider installation fails with the error: "cannot unpack package: failed to fetch package digest from remote: serviceaccounts "crossplane" not found"
https://github.com/upbound/universal-crossplane/blob/main/cluster/charts/universal-crossplane/values.yaml#L260

The nameOverride also overrides the name of the serviceaccount to the new name in the upbound but the upstream crossplane does not expose this value in its values.yaml, although the  _helpers.tpl file does consider a possibility for .Values.nameOverride.
https://github.com/crossplane/crossplane/blob/master/cluster/charts/crossplane/templates/_helpers.tpl#L6

Therefore it still expects a serviceaccount with the default name "crossplane" to exist.

This looks to me as a bug which needs to be fixed. For the time being, is there any recommendation for a workaround?

**Comment by saion-chatterjee** [comment] 2023-09-13 18:51
> Hi @turkenf I faced the same issue. I am able to reproduce it in the following way:
> 
> It seems the uxp installation does not work e2e if the **nameOverride** in _values.yaml_ is anything other than the default value "crossplane". I tried installing it with a different name and the helm chart for uxp is installed but after this the Provider installation fails with the error: `"cannot unpack package: failed to fetch package digest from remote: serviceaccounts "crossplane" not found"` https://github.com/upbound/universal-crossplane/blob/main/cluster/charts/universal-crossplane/values.yaml#L260
> 
> The nameOverride also overrides the name of the serviceaccount to the new name in the upbound but the upstream crossplane does not expose this value in its values.yaml, although the _helpers.tpl file does consider a possibility for .Values.nameOverride. https://github.com/crossplane/crossplane/blob/master/cluster/charts/crossplane/templates/_helpers.tpl#L6
> 
> Therefore it still expects a serviceaccount with the default name "crossplane" to exist.
> 
> This looks to me as a bug which needs to be fixed. For the time being, is there any recommendation for a workaround?

update to 1.13 seems to have solved the issue. It was fixed upstream as part of another feature pr. Thanks to @phisco for pointing it out

**Comment by phisco** [comment] 2024-02-09 10:40
Thanks for the updates, everyone. It looks like updating to version 1.13 has resolved the issue. I'm going to close this for now, but if you encounter any further problems, please feel free to reopen it.

**Closed by phisco** 2024-02-09 10:40 UTC
Labels: needs:triage, needs:information, community
